### ISSUE TITLE
how to handle empty string

### ISSUE THREAD

**Issue by adeds** [faranjit/currency_edittext#11]
this is my my xml : 
  <faranjit.currency.edittext.CurrencyEditText
            android:id="@+id/input_salary"
            style="@style/MotoranFormInput"
            android:layout_marginHorizontal="16dp"
            android:layout_marginTop="7dp"
            android:hint="Rp"
            android:imeOptions="actionDone"
            android:inputType="number"
            android:maxLength="13"
            app:groupDivider="."
            app:locale="in_ID"
            app:monetaryDivider="."
            app:showSymbol="true" />

when i texting, its work normaly, but if i pressed backspace until empty, the app is crashed with error :

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: id.motoran, PID: 32006
    java.lang.NumberFormatException: empty String
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1842)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:539)
        at faranjit.currency.edittext.CurrencyEditText.format(CurrencyEditText.java:190)
        at faranjit.currency.edittext.CurrencyEditText.access$300(CurrencyEditText.java:22)
        at faranjit.currency.edittext.CurrencyEditText$1.onTextChanged(CurrencyEditText.java:171)

**Comment by adeds** [comment]
if u resolved this issue on the new commit, how i can implement at gradle ? is still version 1.0.1 ?
i cant fount new code on the new commit

**Comment by adeds** [comment]
is this lib deprecated?
